<a href="https://colab.research.google.com/github/ArnabSen08/Machine-Learning-Code/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pip --upgrade --user -q --no-warn-script-location
!pip install numpy pandas sklearn matplotlib --user -q --no-warn-script-location

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 21.8 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [2]:
import IPython
IPython.Application.instance().kernel.do_shutdown(True)

{'status': 'ok', 'restart': True}

In [1]:
# Importing required libraries
import numpy as np
import pandas as pd
# Reading the dataset
dataset = pd.read_csv('https://gitlab.com/AnalyticsIndiaMagazine/practicedatasets/-/raw/main/bootcamp/multiple_linear_regression/50_Startups.csv')
# Checking top 5 rows
dataset.head()
#Checking shape of the dataset
dataset.shape

(50, 5)

In [2]:
#Defining Features
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print('Shape of the input features:', x.shape)
print('Shape of the output features:', y.shape)
print(x)
dataset['State'].value_counts()

Shape of the input features: (50, 4)
Shape of the output features: (50,)
[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.4

New York      17
California    17
Florida       16
Name: State, dtype: int64

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3] )], remainder='passthrough' )
x= np.array(ct.fit_transform(x))
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size = 0.2, random_state = 0)
print('Shape of the training patterns:', x_train.shape, y_train.shape)
print('Shape of the test patterns:', x_test.shape, y_test.shape)

Shape of the training patterns: (40, 6) (40,)
Shape of the test patterns: (10, 6) (10,)


In [5]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)
print('The regression coefficients are:', regressor.coef_)
print('The intercept', regressor.intercept_)

The regression coefficients are: [ 8.66383692e+01 -8.72645791e+02  7.86007422e+02  7.73467193e-01
  3.28845975e-02  3.66100259e-02]
The intercept 42467.52924853204


In [7]:
y_pred = regressor.predict(x_test)
pd.DataFrame(data={'Predicted Profit': y_pred, 'Actual Profit': y_test})

Predicted Profit  Actual Profit
0     103015.201598      103282.38
1     132582.277608      144259.40
2     132447.738452      146121.95
3      71976.098513       77798.83
4     178537.482211      191050.39
5     116161.242302      105008.31
6      67851.692097       81229.06
7      98791.733747       97483.56
8     113969.435330      110352.25
9     167921.065696      166187.94

In [8]:
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error( y_test, y_pred)
print('Mean Squared Error is:', MSE)
import math
RMSE = math.sqrt(MSE)
print('Root Mean Squared Error is:', RMSE)
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print('R-Squared is:', r2)
adj = 1 - (
    (1-r2)*(x_train.shape[0]-1)/
    (x_train.shape[0]- x_train.shape[1]-1)
)
print('Adjusted R-Squared is:', adj)

Mean Squared Error is: 83502864.03256583
Root Mean Squared Error is: 9137.990152794313
R-Squared is: 0.9347068473282515
Adjusted R-Squared is: 0.9228353650242972
